# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{featured_model}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["bendycode", "listrophy", "arta", "randland", "jaym3s"]
  s.date = %q{2010-03-17}
  s.description = %q{Additional steps that add a bunch of functionality for creating models with one line}
  s.email = %q{stephen@bendyworks.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "README.textile"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "README.textile",
     "Rakefile",
     "VERSION",
     "featured_model.gemspec",
     "features/support/env.rb",
     "lib/featured_model.rb",
     "lib/featured_model/steps.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/bendyworks/featured_model}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Fancy steps for creating models}
  s.test_files = [
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<fixjour>, [">= 0"])
    else
      s.add_dependency(%q<fixjour>, [">= 0"])
    end
  else
    s.add_dependency(%q<fixjour>, [">= 0"])
  end
end

